from pyformlang.fst import FST
import random

def transformate_antonyms():
    fst = FST()
    for word, antonyms in antonyms_dict.items():
        fst.add_transitions([(0, word, 1, [random.choice(antonyms)])])

    fst.add_start_state(0)
    fst.add_final_state(1)

    return fst

# Diccionario de antónimos
antonyms_dict = {
    "abundant": ["scarce", "limited", "meager"],
    "angry": ["calm", "happy", "peaceful"],
    "ancient": ["modern", "new", "recent"],
    "ascend": ["descend", "drop", "fall"],
    "asleep": ["awake", "alert", "conscious"],
    "attentive": ["distracted", "inattentive", "neglectful"],
    "big": ["small", "tiny", "little"],
    "bright": ["dim", "dull", "dark"],
    "brilliant": ["stupid", "dull", "foolish"],
    "busy": ["idle", "inactive", "lazy"],
    "calm": ["agitated", "excited", "nervous"],
    "careful": ["careless", "reckless", "negligent"],
    "cheap": ["expensive", "costly", "high-priced"],
    "clean": ["dirty", "filthy", "soiled"],
    "clear": ["unclear", "confused", "cloudy"],
    "close": ["far", "distant", "remote"],
    "cold": ["hot", "warm", "tepid"],
    "complicated": ["simple", "easy", "straightforward"],
    "complete": ["incomplete", "partial", "deficient"],
    "confident": ["doubtful", "insecure", "uncertain"],
    "content": ["discontent", "unhappy", "dissatisfied"],
    "correct": ["incorrect", "wrong", "false"],
    "dark": ["light", "bright", "illuminated"],
    "deep": ["shallow", "superficial", "flat"],
    "difficult": ["easy", "simple", "straightforward"],
    "dirty": ["clean", "pure", "spotless"],
    "distant": ["near", "close", "adjacent"],
    "dull": ["sharp", "bright", "exciting"],
    "easy": ["difficult", "hard", "challenging"],
    "empty": ["full", "filled", "occupied"],
    "equal": ["unequal", "different", "disparate"],
    "false": ["true", "correct", "accurate"],
    "fast": ["slow", "sluggish", "lethargic"],
    "feminine": ["masculine", "male", "manly"],
    "frequent": ["rare", "infrequent", "seldom"],
    "friendly": ["hostile", "unfriendly", "cold"],
    "generous": ["stingy", "selfish", "greedy"],
    "happy": ["sad", "unhappy", "miserable"],
    "hard": ["soft", "easy", "gentle"],
    "harsh": ["gentle", "soft", "mild"],
    "high": ["low", "short", "small"],
    "hopeful": ["hopeless", "despairing", "pessimistic"],
    "hot": ["cold", "cool", "chilly"],
    "ignorant": ["knowledgeable", "informed", "educated"],
    "important": ["unimportant", "trivial", "insignificant"],
    "in": ["out", "outside", "away"],
    "included": ["excluded", "omitted", "left out"],
    "independent": ["dependent", "reliant", "subservient"],
    "kind": ["cruel", "unkind", "mean"],
    "large": ["small", "tiny", "little"],
    "late": ["early", "prompt", "on time"],
    "lazy": ["active", "busy", "energetic"],
    "light": ["heavy", "dark", "weighty"],
    "long": ["short", "brief", "tiny"],
    "loud": ["quiet", "silent", "soft"],
    "love": ["hate", "dislike", "loathe"],
    "major": ["minor", "trivial", "insignificant"],
    "male": ["female", "woman", "feminine"],
    "new": ["old", "ancient", "outdated"],
    "noisy": ["quiet", "silent", "calm"],
    "optimistic": ["pessimistic", "cynical", "negative"],
    "open": ["closed", "shut", "blocked"],
    "positive": ["negative", "pessimistic", "neutral"],
    "private": ["public", "open", "shared"],
    "pure": ["impure", "dirty", "contaminated"],
    "quick": ["slow", "lethargic", "delayed"],
    "quiet": ["loud", "noisy", "boisterous"],
    "rich": ["poor", "needy", "impoverished"],
    "safe": ["dangerous", "unsafe", "hazardous"],
    "sane": ["insane", "crazy", "mad"],
    "simple": ["complex", "difficult", "complicated"],
    "slow": ["fast", "quick", "speedy"],
    "soft": ["hard", "firm", "solid"],
    "sober": ["drunk", "intoxicated", "high"],
    "strong": ["weak", "fragile", "delicate"],
    "tall": ["short", "small", "tiny"],
    "thin": ["thick", "fat", "plump"],
    "true": ["false", "incorrect", "wrong"],
    "uncertain": ["certain", "sure", "confident"],
    "unhappy": ["happy", "joyful", "content"],
    "weak": ["strong", "powerful", "robust"],
    "wide": ["narrow", "tight", "small"],
    "young": ["old", "aged", "elderly"],
}