from pyformlang.fst import FST
import random

def transformate_synonyms():
    fst = FST()
    for word, synonyms in synonyms_dict.items():
        fst.add_transitions([(0, word, 1, [random.choice(synonyms)])])

    fst.add_start_state(0)
    fst.add_final_state(1)

    return fst

# Diccionario de sinónimos
synonyms_dict = {
    "abundant": ["plentiful", "ample"],
    "angry": ["mad", "furious"],
    "anxious": ["nervous", "worried"],
    "beautiful": ["attractive", "lovely"],
    "big": ["large", "huge"],
    "bored": ["uninterested", "weary"],
    "brave": ["courageous", "fearless"],
    "calm": ["peaceful", "tranquil"],
    "careful": ["cautious", "attentive"],
    "cheerful": ["happy", "joyful"],
    "clever": ["smart", "intelligent"],
    "cold": ["chilly", "cool"],
    "confident": ["self-assured", "certain"],
    "crazy": ["insane", "mad"],
    "curious": ["inquisitive", "eager"],
    "dangerous": ["hazardous", "risky"],
    "dark": ["dim", "gloomy"],
    "dear": ["beloved", "cherished"],
    "delighted": ["pleased", "happy"],
    "determined": ["resolute", "persistent"],
    "difficult": ["hard", "challenging"],
    "eager": ["enthusiastic", "keen"],
    "easy": ["simple", "effortless"],
    "elegant": ["graceful", "stylish"],
    "enormous": ["huge", "gigantic"],
    "excited": ["enthusiastic", "thrilled"],
    "famous": ["renowned", "well-known"],
    "fearful": ["afraid", "scared"],
    "friendly": ["kind", "welcoming"],
    "funny": ["amusing", "humorous"],
    "generous": ["giving", "charitable"],
    "gentle": ["kind", "soft"],
    "good": ["great", "excellent"],
    "happy": ["joyful", "content"],
    "hard": ["difficult", "challenging"],
    "healthy": ["fit", "well"],
    "helpful": ["useful", "beneficial"],
    "honest": ["truthful", "sincere"],
    "hot": ["warm", "scorching"],
    "huge": ["enormous", "gigantic"],
    "hungry": ["starving", "ravenous"],
    "important": ["significant", "crucial"],
    "incredible": ["amazing", "unbelievable"],
    "interested": ["curious", "engaged"],
    "kind": ["friendly", "gentle"],
    "lazy": ["idle", "sluggish"],
    "light": ["bright", "luminous"],
    "lonely": ["isolated", "alone"],
    "loud": ["noisy", "boisterous"],
    "lovely": ["beautiful", "charming"],
    "lucky": ["fortunate", "blessed"],
    "mad": ["angry", "furious"],
    "many": ["numerous", "countless"],
    "mysterious": ["enigmatic", "puzzling"],
    "neat": ["tidy", "organized"],
    "new": ["recent", "fresh"],
    "nice": ["pleasant", "kind"],
    "old": ["ancient", "aged"],
    "ordinary": ["usual", "common"],
    "peaceful": ["calm", "tranquil"],
    "perfect": ["flawless", "ideal"],
    "pleased": ["delighted", "happy"],
    "polite": ["courteous", "respectful"],
    "powerful": ["strong", "potent"],
    "proud": ["pleased", "satisfied"],
    "quick": ["fast", "swift"],
    "quiet": ["silent", "calm"],
    "rare": ["uncommon", "infrequent"],
    "rich": ["wealthy", "affluent"],
    "sad": ["unhappy", "sorrowful"],
    "safe": ["secure", "protected"],
    "satisfied": ["content", "pleased"],
    "scared": ["afraid", "fearful"],
    "silly": ["foolish", "absurd"],
    "simple": ["easy", "straightforward"],
    "smart": ["clever", "intelligent"],
    "strong": ["powerful", "sturdy"],
    "successful": ["prosperous", "victorious"],
    "surprised": ["astonished", "shocked"],
    "tall": ["high", "lofty"],
    "tired": ["weary", "exhausted"],
    "tricky": ["challenging", "difficult"],
    "unhappy": ["sad", "miserable"],
    "unique": ["distinct", "special"],
    "warm": ["hot", "tepid"],
    "weird": ["strange", "odd"],
    "well": ["healthy", "fit"],
    "wild": ["untamed", "fierce"],
    "wise": ["sensible", "knowledgeable"],
    "witty": ["humorous", "clever"],
    "young": ["juvenile", "youthful"],
}